{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "8665930b-80ea-4cda-9325-b2a779fb08fd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting geopandas\n",
      "  Using cached geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)\n",
      "Requirement already satisfied: numpy>=1.22 in /opt/anaconda3/envs/taxidev/lib/python3.9/site-packages (from geopandas) (1.26.4)\n",
      "Collecting pyogrio>=0.7.2 (from geopandas)\n",
      "  Using cached pyogrio-0.9.0.tar.gz (352 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h  Preparing metadata (pyproject.toml) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mPreparing metadata \u001b[0m\u001b[1;32m(\u001b[0m\u001b[32mpyproject.toml\u001b[0m\u001b[1;32m)\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[27 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 353, in <module>\n",
      "  \u001b[31m   \u001b[0m     main()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 335, in main\n",
      "  \u001b[31m   \u001b[0m     json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 149, in prepare_metadata_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     return hook(metadata_directory, config_settings)\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-iexlayq8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py\", line 368, in prepare_metadata_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     self.run_setup()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-iexlayq8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py\", line 497, in run_setup\n",
      "  \u001b[31m   \u001b[0m     super().run_setup(setup_script=setup_script)\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-iexlayq8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py\", line 313, in run_setup\n",
      "  \u001b[31m   \u001b[0m     exec(code, locals())\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 154, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 129, in get_gdal_config\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 85, in get_gdal_config\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 85, in <dictcomp>\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 39, in read_response\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/subprocess.py\", line 424, in check_output\n",
      "  \u001b[31m   \u001b[0m     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/subprocess.py\", line 505, in run\n",
      "  \u001b[31m   \u001b[0m     with Popen(*popenargs, **kwargs) as process:\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/subprocess.py\", line 951, in __init__\n",
      "  \u001b[31m   \u001b[0m     self._execute_child(args, executable, preexec_fn, close_fds,\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/subprocess.py\", line 1837, in _execute_child\n",
      "  \u001b[31m   \u001b[0m     raise child_exception_type(errno_num, err_msg, err_filename)\n",
      "  \u001b[31m   \u001b[0m FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for details.\n",
      "\u001b[?25hNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "# you have to install\n",
    "#First\n",
    "#%pip install geopandas\n",
    "#then after \n",
    "#%pip install geopandas folium"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "20ab5c86-1c38-431e-8fbe-2dc5ec238447",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting gdal\n",
      "  Downloading gdal-3.9.1.tar.gz (840 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m840.3/840.3 kB\u001b[0m \u001b[31m7.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25h  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mGetting requirements to build wheel\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[86 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Using numpy 2.0.0\n",
      "  \u001b[31m   \u001b[0m running egg_info\n",
      "  \u001b[31m   \u001b[0m writing gdal-utils/GDAL.egg-info/PKG-INFO\n",
      "  \u001b[31m   \u001b[0m writing dependency_links to gdal-utils/GDAL.egg-info/dependency_links.txt\n",
      "  \u001b[31m   \u001b[0m writing entry points to gdal-utils/GDAL.egg-info/entry_points.txt\n",
      "  \u001b[31m   \u001b[0m writing requirements to gdal-utils/GDAL.egg-info/requires.txt\n",
      "  \u001b[31m   \u001b[0m writing top-level names to gdal-utils/GDAL.egg-info/top_level.txt\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 91, in fetch_config\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/subprocess.py\", line 951, in __init__\n",
      "  \u001b[31m   \u001b[0m     self._execute_child(args, executable, preexec_fn, close_fds,\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/subprocess.py\", line 1837, in _execute_child\n",
      "  \u001b[31m   \u001b[0m     raise child_exception_type(errno_num, err_msg, err_filename)\n",
      "  \u001b[31m   \u001b[0m FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m During handling of the above exception, another exception occurred:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 231, in get_gdal_config\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 94, in fetch_config\n",
      "  \u001b[31m   \u001b[0m __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m During handling of the above exception, another exception occurred:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 353, in <module>\n",
      "  \u001b[31m   \u001b[0m     main()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 335, in main\n",
      "  \u001b[31m   \u001b[0m     json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 118, in get_requires_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     return hook(config_settings)\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py\", line 327, in get_requires_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     return self._get_build_requires(config_settings, requirements=[])\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py\", line 297, in _get_build_requires\n",
      "  \u001b[31m   \u001b[0m     self.run_setup()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py\", line 313, in run_setup\n",
      "  \u001b[31m   \u001b[0m     exec(code, locals())\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 421, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/__init__.py\", line 103, in setup\n",
      "  \u001b[31m   \u001b[0m     return distutils.core.setup(**attrs)\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py\", line 184, in setup\n",
      "  \u001b[31m   \u001b[0m     return run_commands(dist)\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py\", line 200, in run_commands\n",
      "  \u001b[31m   \u001b[0m     dist.run_commands()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py\", line 970, in run_commands\n",
      "  \u001b[31m   \u001b[0m     self.run_command(cmd)\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/dist.py\", line 974, in run_command\n",
      "  \u001b[31m   \u001b[0m     super().run_command(command)\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py\", line 989, in run_command\n",
      "  \u001b[31m   \u001b[0m     cmd_obj.run()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py\", line 321, in run\n",
      "  \u001b[31m   \u001b[0m     self.find_sources()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py\", line 329, in find_sources\n",
      "  \u001b[31m   \u001b[0m     mm.run()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py\", line 550, in run\n",
      "  \u001b[31m   \u001b[0m     self.add_defaults()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py\", line 588, in add_defaults\n",
      "  \u001b[31m   \u001b[0m     sdist.add_defaults(self)\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/command/sdist.py\", line 102, in add_defaults\n",
      "  \u001b[31m   \u001b[0m     super().add_defaults()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py\", line 250, in add_defaults\n",
      "  \u001b[31m   \u001b[0m     self._add_defaults_ext()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py\", line 334, in _add_defaults_ext\n",
      "  \u001b[31m   \u001b[0m     build_ext = self.get_finalized_command('build_ext')\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py\", line 303, in get_finalized_command\n",
      "  \u001b[31m   \u001b[0m     cmd_obj.ensure_finalized()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/m1/v2p5dlc135x8ctp72qfss6200000gn/T/pip-build-env-0yslxp5y/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py\", line 111, in ensure_finalized\n",
      "  \u001b[31m   \u001b[0m     self.finalize_options()\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 307, in finalize_options\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 237, in get_gdal_config\n",
      "  \u001b[31m   \u001b[0m __main__.gdal_config_error: Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 91, in fetch_config\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/subprocess.py\", line 951, in __init__\n",
      "  \u001b[31m   \u001b[0m     self._execute_child(args, executable, preexec_fn, close_fds,\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/envs/taxidev/lib/python3.9/subprocess.py\", line 1837, in _execute_child\n",
      "  \u001b[31m   \u001b[0m     raise child_exception_type(errno_num, err_msg, err_filename)\n",
      "  \u001b[31m   \u001b[0m FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m During handling of the above exception, another exception occurred:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 231, in get_gdal_config\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 94, in fetch_config\n",
      "  \u001b[31m   \u001b[0m gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Could not find gdal-config. Make sure you have installed the GDAL native library and development headers.\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m \u001b[32mGetting requirements to build wheel\u001b[0m did not run successfully.\n",
      "\u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25hNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install gdal"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f05963ed-86ac-4b3d-bfbf-d70932284865",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:taxidev] *",
   "language": "python",
   "name": "conda-env-taxidev-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
